---
#info: Executes a shellscript as Ansible playbook and writes a log file
- hosts: all
  gather_facts: no
  tasks:

    - name: Script {{ ww_script }}
      script: '{{ ww_path }}{{ ww_script }}'
      register: ww_run_sh_out

    - name: Save log file
      include_role: name=servermonkey.ww_logger
      vars:
        ww_msg: '{{ ww_run_sh_out.stdout }}'
        ww_logfile: '{{ ww_role }}_{{ ww_script }}'