---
#info: Executes a task from a role as Ansible playbook
- hosts: all
  gather_facts: no
  tasks:

    - name: Task
      include_role:
        name: '{{ ww_role }}'
        tasks_from: '{{ ww_script }}'